### ISSUE TITLE
name 'unicode' is not defined

### ISSUE THREAD

**Issue by GunnGrave** [sonya75/starbucks-botdetection-cracked#3]
Traceback (most recent call last):
  File "C:\Users\user\Desktop\starbucks-sonya75\starbuckslogin.py", line 1, in <module>
    from sensordata import BotDetector
  File "C:\Users\user\Desktop\starbucks-sonya75\sensordata.py", line 3, in <module>
    from superpack import *
  File "C:\Users\user\Desktop\starbucks-sonya75\superpack.py", line 236, in <module>
    unicode:Encoder.writeStr,
NameError: name 'unicode' is not defined

i am having this problem with both  py3.8 mac and py3.7 win64
any help please

**Comment by playlikedendi** [comment]
try 2.7 version
3+ dont use unicode
